# Site
title: Wes
description: Talvez uma ideia, talvez um pensamento
url: https://taylantatli.github.io/Halve
logo: logobranco.png                                       # Site logo
locale: pt_BR

# Left Block Images
background:
  homepage: images/home.png                           # this image will be shown on homepage's left block
  post-list: images/unsplash-image-10.jpg             # this image will be shown on post list page
  default-post: images/unsplash-gallery-image-3.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
email:             wesnunes@outlook.com
#google.plus:        username
#twitter:            username
facebook:           manifestodosquadrinhos
#github:             WesRabbit
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          wesnunes
#xing:              username
#instagram:          username
#lastfm:            username
tumblr:            manifestodosquadrinhos
#pinterest:         username
#foursquare:        username
steam:              wescomics
#dribbble:          username
#youtube:           username
soundcloud:        messofthewes
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
behance:           wesnunes

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
